# Test for getting list of chercheurs with pagination
GET http://127.0.0.1:8000/tracker/chercheurs/?page=1
Accept: application/json

###

# Test for getting list of chercheurs
GET http://127.0.0.1:8000/tracker/chercheurs/
Accept: application/json

###

# Test for creating a new chercheur
POST http://127.0.0.1:8000/tracker/chercheurs/
Content-Type: application/json

{
  "nom": "John Doe",
  "specialite": "Computer Science"
}

###

# Test for getting a specific chercheur by ID
GET http://127.0.0.1:8000/tracker/chercheurs/74/
Accept: application/json

###

# Test for updating a chercheur by ID
PUT http://127.0.0.1:8000/tracker/chercheurs/74/
Content-Type: application/json

{
  "nom": "Jane Doe",
  "specialite": "Data Science"
}

###

# Test for deleting a chercheur by ID
DELETE http://127.0.0.1:8000/tracker/chercheurs/74/
Accept: application/json

###

# Test for getting list of projets with pagination
GET http://127.0.0.1:8000/tracker/projets/?page=1
Accept: application/json

###

# Test for creating a new projet
POST http://127.0.0.1:8000/tracker/projets/
Content-Type: application/json

{
  "titre": "New Project",
  "description": "Project Description",
  "date_debut": "2024-06-01",
  "date_fin_prevue": "2025-06-01",
  "chef_de_projet": 23,
  "chercheurs": [57, 61]
}

###

# Test for getting a specific projet by ID
GET http://127.0.0.1:8000/tracker/projets/51/
Accept: application/json

###

# Test for updating a projet by ID
PUT http://127.0.0.1:8000/tracker/projets/51/
Content-Type: application/json

{
  "titre": "Updated Project",
  "description": "Updated Description",
  "date_debut": "2024-06-01",
  "date_fin_prevue": "2025-06-01",
  "chef_de_projet": 61,
  "chercheurs": [23, 57]
}

###

# Test for deleting a projet by ID
DELETE http://127.0.0.1:8000/tracker/projets/51/
Accept: application/json

###

# Test for getting list of publications with pagination
GET http://127.0.0.1:8000/tracker/publications/?page=1
Accept: application/json

###

# Test for creating a new publication
POST http://127.0.0.1:8000/tracker/publications/
Content-Type: application/json

{
  "titre": "New Publication",
  "resume": "Publication Summary",
  "projet": 4,
  "date_publication": "2024-06-01"
}

###

# Test for getting a specific publication by ID
GET http://127.0.0.1:8000/tracker/publications/46/
Accept: application/json

###

# Test for updating a publication by ID
PUT http://127.0.0.1:8000/tracker/publications/46/
Content-Type: application/json

{
  "titre": "Updated Publication",
  "resume": "Updated Summary",
  "projet": 4,
  "date_publication": "2024-06-01"
}

###

# Test for deleting a publication by ID
DELETE http://127.0.0.1:8000/tracker/publications/46/
Accept: application/json
